language: python
python:
      - "3.7"

install:
       - pip install -r requirements.txt

before_script:
       - python sweDjangoTutorial/mysite/manage.py migrate
       - python -m pip install flake8
script:
       - python sweDjangoTutorial/mysite/manage.py test
       - black --check .
       - flake8 .
       - coverage run sweDjangoTutorial/mysite/manage.py test
       - coveralls

before_deploy:
       - cd mysite





deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted ="
  secret_access_key:
    secure: "Encypted ="
  region: "us-east-1"
  app: "swePolls"
  env: "envPolls"
  bucket_name: "the-target-S3-bucket"

  on:
  repo: aaqilkhoja/swe1-app   

  branch:
   - main
