language: python
python:
      - "3.7"

env:
       - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
       - AWS_SECRET_KEY=$AWS_SECRET_KEY

install:
       - pip install -r requirements.txt

before_script:
       - python mysite/manage.py migrate
       - python -m pip install flake8
script:
       - python mysite/manage.py test
       - black --check .
       - flake8 .
       - coverage run mysite/manage.py test
       - coveralls

before_deploy:
       - cd mysite





deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: ${AWS_ACCESS_KEY}
  secret_access_key:
    secure: ${AWS_SECRET_KEY}
  region: "us-west-2"
  app: "assignment-2"
  env: "assignment2-env"
  bucket_name: "elasticbeanstalk-us-west-2-730437625654"

  on:
    repo: aaqilkhoja/swe1-app   

    branch:
     - main
