language: python
python:
      - "3.7"

install:
       - pip install -r requirements.txt

before_script:
       - python sweDjangoTutorial/mysite/manage.py migrate

script:
       - python sweDjangoTutorial/mysite/manage.py test
